name: Build Provider

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.24.6'
  PROVIDER_NAME: 'kubevirt'

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build provider
        run: |
          mkdir -p bin
          go build -o bin/terraform-provider-kubevirt .
          echo "Build completed"
