# Copyright (c) 2025 NRP-Nautilus
# SPDX-License-Identifier: MPL-2.0

name: Build and Release Terraform Provider

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.24.6'
  PROVIDER_NAME: 'kubevirt'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Initialize Go module
        run: |
          go mod tidy
          go mod download
          go mod verify

      - name: Build provider
        run: |
          mkdir -p bin
          VERSION="v0.1.${{ github.run_number }}"
          echo "Building version: $VERSION"
          
          # Build for all platforms
          GOOS=linux GOARCH=amd64 go build -o bin/terraform-provider-kubevirt-linux-amd64 .
          GOOS=linux GOARCH=arm64 go build -o bin/terraform-provider-kubevirt-linux-arm64 .
          GOOS=darwin GOARCH=amd64 go build -o bin/terraform-provider-kubevirt-darwin-amd64 .
          GOOS=darwin GOARCH=arm64 go build -o bin/terraform-provider-kubevirt-darwin-arm64 .
          
          # Create zip files FIRST
          cd bin
          zip "terraform-provider-${PROVIDER_NAME}_${VERSION#v}_linux_amd64.zip" terraform-provider-kubevirt-linux-amd64
          zip "terraform-provider-${PROVIDER_NAME}_${VERSION#v}_linux_arm64.zip" terraform-provider-kubevirt-linux-arm64
          zip "terraform-provider-${PROVIDER_NAME}_${VERSION#v}_darwin_amd64.zip" terraform-provider-kubevirt-darwin-amd64
          zip "terraform-provider-${PROVIDER_NAME}_${VERSION#v}_darwin_arm64.zip" terraform-provider-kubevirt-darwin-arm64
          
          # THEN rename binaries inside zip files to correct Terraform provider name
          echo "Renaming binaries inside zip files to terraform-provider-kubevirt..."
          for zipfile in *.zip; do
            echo "Processing $zipfile..."
            # Extract the zip
            unzip -o -q "$zipfile"
            # Get the binary name (should be terraform-provider-kubevirt-*)
            BINARY_NAME=$(ls terraform-provider-kubevirt-*)
            # Rename it to the correct Terraform provider name
            mv "$BINARY_NAME" terraform-provider-kubevirt
            # Recreate the zip with the correct binary name
            rm "$zipfile"
            zip "$zipfile" terraform-provider-kubevirt
            # Clean up extracted files
            rm terraform-provider-kubevirt
          done
          
          # Copy manifest file to bin directory
          echo "Copying terraform-registry-manifest.json to bin directory..."
          cp ../terraform-registry-manifest.json .
          
          # Generate checksums
          shasum -a 256 *.zip > "terraform-provider-${PROVIDER_NAME}_${VERSION#v}_SHA256SUMS"
          
          echo "Files in bin directory:"
          ls -la

      - name: Setup GPG
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --import

      - name: Sign SHA256SUMS
        run: |
          cd bin
          VERSION="v0.1.${{ github.run_number }}"
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --detach-sign "terraform-provider-${PROVIDER_NAME}_${VERSION#v}_SHA256SUMS"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/terraform-registry-manifest.json
            bin/terraform-provider-kubevirt_0.1.${{ github.run_number }}_SHA256SUMS
            bin/terraform-provider-kubevirt_0.1.${{ github.run_number }}_SHA256SUMS.sig
            bin/terraform-provider-kubevirt_0.1.${{ github.run_number }}_linux_amd64.zip
            bin/terraform-provider-kubevirt_0.1.${{ github.run_number }}_linux_arm64.zip
            bin/terraform-provider-kubevirt_0.1.${{ github.run_number }}_darwin_amd64.zip
            bin/terraform-provider-kubevirt_0.1.${{ github.run_number }}_darwin_arm64.zip
          generate_release_notes: true
          tag_name: "v0.1.${{ github.run_number }}"
          name: "Release v0.1.${{ github.run_number }} - ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
