name: Continuous Build Terraform Provider

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.21'
  PROVIDER_NAME: 'kubevirt'

# Add explicit permissions for creating releases
permissions:
  contents: write
  packages: write

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Terraform
        run: |
          wget -O terraform.zip https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
          unzip terraform.zip
          sudo mv terraform /usr/local/bin/
          terraform version

      - name: Download dependencies
        run: |
          go mod download
          go mod verify

      - name: Run tests
        run: |
          go test -v ./...
          go vet ./...
          go fmt ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build provider
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 go build -o bin/terraform-provider-${PROVIDER_NAME}_${GITHUB_SHA} .
          GOOS=darwin GOARCH=amd64 go build -o bin/terraform-provider-${PROVIDER_NAME}_${GITHUB_SHA}_darwin .
          ls -la bin/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: provider-binaries
          path: bin/
          retention-days: 7

      - name: Generate SHA256 checksums
        run: |
          cd bin
          shasum -a 256 * > SHA256SUMS
          echo "SHA256SUMS content:"
          cat SHA256SUMS
          echo "Current directory contents:"
          ls -la

      - name: Setup GPG
        run: |
          echo "Setting up GPG..."
          echo "GPG_PRIVATE_KEY exists: ${{ secrets.GPG_PRIVATE_KEY != '' }}"
          echo "GPG_PASSPHRASE exists: ${{ secrets.GPG_PASSPHRASE != '' }}"
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --yes --import
          echo "GPG setup completed"

      - name: Sign SHA256SUMS
        run: |
          echo "Signing SHA256SUMS..."
          cd bin
          echo "${{ secrets.GPG_PASSPHRASE }}" | gpg --batch --yes --passphrase-fd 0 --pinentry-mode loopback --detach-sign --armor SHA256SUMS
          echo "Signed SHA256SUMS.asc content:"
          cat SHA256SUMS.asc
          echo "Signing completed"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/SHA256SUMS
            bin/SHA256SUMS.asc
            bin/terraform-provider-kubevirt_*
          generate_release_notes: true
          tag_name: "v0.1.${{ github.run_number }}"
          name: "Release v0.1.${{ github.run_number }} - ${{ github.sha }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# Force fresh workflow run - Thu Aug 21 22:40:57 EDT 2025
